### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by Dream-Master** [Corosauce/CoroUtil#5]
The Server Crash two times.

I using Zombi Awareness 1.9.6 and Coro util 1.1.3

Do i have to using 1.1.1 because it is in the zip File?

Crash Reports
https://gist.github.com/Dream-Master/90eee00ff080980c0d94#file-gistfile1-txt
https://gist.github.com/Dream-Master/dedfa839ac259dec9e6b#file-gistfile1-txt

**Comment by Bogdan-G** [comment]
Hello. I'm use forge 1492, coroutil 1.1.3, ZA 1.9.6, weather2 2.3.9, game no crash O_o
`JVM Flags: 2 total; -XX:MaxPermSize=1024m -Xmx8G`
MaxPermSize=1024m 
wut

try the test with a forge in 1492 ie 150 cauldron build.
jvm arguments: -Xincgc -xmx4g -XX:MaxPermSize=286m -XX:+AggressiveOpts -XX:+UseCompressedOops -XX:+UseStringCache

**Comment by Dream-Master** [comment]
Ok thanks will try it.

**Comment by Namikon** [comment]
I just want to mention that this crash does occour randomly, and not all the time. But if it happens, you have to remove the mod in order to get the Server back online. It seems that an entity gets "stuck" somewhere (In a wall?). As soon as the chunk with this Entity is loaded, in our case when the player near that entity logged back in after restart, it crashes again with the out of heap space error.

**Comment by Bogdan-G** [comment]
@Namikon The fact that the degree of weather2 good passes or gets stuck in the blocks, but quickly despawned.

**Comment by Corosauce** [comment]
CoroUtil likes to make a mirror copy of the chunk data in order to work with it on another thread. This can increase the amount of memory required, so either you just need to allocate even more memory, or it's an old issue where certain dimensions just don't play well with my system, if you don't even need my entities active in the dimension with the problem, you can get the name of the dimension and blacklist it from getting cached via CoroUtil.cfg, using chunkCacheDimensionBlacklist_IDs for ID, or chunkCacheDimensionBlacklist_Names for name if its a dynamically allocated dimension, or set chunkCacheOverworldOnly to true to make it only work on overworld as a more agressive solution.

**Comment by ProsperCraft** [comment]
http://pastebin.com/e3xFcDTJ

We don't have zombie, only weather mod.

**Comment by ProsperCraft** [comment]
Setting chunkCacheOverworldOnly=true changed our ram usage from 10 gigs to 3 gigs on my modpack with 50+ dims.

**Comment by ProsperCraft** [comment]
https://github.com/Corosauce/CoroUtil/issues/10

**Comment by Corosauce** [comment]
Added ability to use the blacklist ID / name feature as a whitelist instead, should help with modpacks that have more dynamic dimensions than static ones you don't want touched by PFQueue https://github.com/Corosauce/CoroUtil/commit/f38849dc784b855b4990517ece31bdb9ef699284
