### ISSUE TITLE
CoroUtil causing major fps drops

### ISSUE THREAD

**Issue by bloxgate** [Corosauce/CoroUtil#9]
I've received several reports from users on a server I administrate that they suffer major FPS drops when they have CoroUtil installed. We've temporarily removed it from the server, but I'd like to keep using your mods that require it. No one has reported any errors in console, just major FPS drops.

**Comment by Corosauce** [comment]
Hmm, just to make sure, when you say FPS drops, you mean for the clients and you dont actually mean TPS drops? Also how many players are on your server usually when this happens?

Also could I get a list of mods that the server use?

**Comment by bloxgate** [comment]
Yes, by FPS drops I do mean for clients. TPS impact was negligible most of the time. However TPS also becomes a problem if the servers under load as CoroUtil seems to be using the same amount of processing time as everything else on the server combined. The FPS issues happen with any number of players, the TPS issues only happen with lots of players or high load on the server.

Mods list:
Advanced Repulsion Systems v59.0.3
Advanced Solar Panels v3.5.1
Another One Bites the Dust 2 v2.8.2
Apple Core v1.1.0
Applied Energistics 2 rv2-stable-10
Armor Status HUD v1.28
AsieLib v0.4.0
Automagy v0.26.3
Baubles v1.0.1.10
Bibliocraft v1.10.6
Big Reactors v0.4.3A
Binnie's Mods 2.0-pre14
Biomes O' Plenty v2.1.0.1390
Blood Magic v1.3.3-13
Botania v1.7-221
BspkrsCore v6.15
Buildcraft v7.0.22
Buildcraft Compat v7.0.9
Carpenter's Blocks v3.3.7-dev
Chisel v2.9.0.3
Chisel Tones v1.0-3
Code Chicken Core v1.0.7.47
COFH Core v3.0.3-303
Computronics v1.5.6
Cookie Core v1.4.0-11
CustomThings v0.0.3-38
Damage Indicators v3.2.3
Dense Ores v1.6.2
Dimensional Anchors v59.0.3
EiraIRC v2.9.387
Electrical Age Beta v1.10-r50
EnderCore v0.1.0.26-beta
EnderIO v2.3.0.417-beta
Ender Storage v1.4.7.37
ExtraCells v2.2.73
ExtraTiC v1.4.5
Extra Utilities v1.2.11
FastCraft v1.21 (via mod download GUI)
Forge MultiPart v1.1.0.331
FlatSigns v2.1.0.19
FlaxBeards Steam Power v0.28.10
Forbidden Magic v0.57
Forestry v3.6.3.20
GraviSuite v2.0.3
Guide-API v1.0.1-20
Hardcore Ender Expansion v1.8.3
Hats v4.0.1
IC2 Nuclear Control v2.2.5a-GoingForTheKill
iChunUtil v4.2.2
Illuminated Bows v1.7.1f
Immibis Core v59.1.2
Immibis' Microblocks v59.1.1
Industrial Craft 2exp v2.2.770
Infernal Mobs v1.6.0
INpureCore v1.0.0B9-62
Inventory Tweaks v1.59-dev-156
Iron Chests 2 v6.0.62.742
JABBA v1.2.1a
KitchenCraft-combo v1.0.0-63
Lib Sandstone v1.0.0
Logistics Pipes v0.9.2.46
LookingGlass v0.2.0.00
Magic Bees v2.2.5
Malisis Core v0.12.9
Malisis Doors 1.9.5
Mantle v0.3.2.188
Mekanism v8.1.7.TPPI-5
Mekanism Generators v8.1.7.252
MineFactory Reloaded v2.8.0-104
MineTweaker 3 v3.0.10B
MmmMmmMmmMmm v1.6
Mobius Core v1.2.5
ModpackTweaks v1.2.0-26
ModularArmour v1.0.18-41
ModTweaker2 v0.9.3
MoreChisels v1.0-25
Morph v0.9.2
Mystcraft 0.12.3.00
Natura v99.04f2bb2
NEI Addons v1.12.12.37
NEI Integration v1.0.12
Nether Ores v2.3.1-18
Not Enough Codecs v0.3-13
Not Enough Items v1.0.5.118
Open Blocks v1.4.4-snapshot-665
Open Computers v1.5.16.726-dev
Open Eye v0.6-snapshot-145
Open Mods Lib v0.8-snapshot-393
Railcraft v9.7.0.0
Random Things v2.2.4
RecipeTweakingCore v1.1.0-8
Red Logic v59.1.11
Redstone Armory v1.2.0-38
Redstone Arsenal v1.1.1-89
Refined Relocation v1.0.8a
Reliquary v1.2.257
Sanguimancy v1.1.9-33
ServerTools BACKUP v2.2.1.24
ServerTools CORE v2.2.0.79
StevesAddons v0.10.16
Steves Carts 2 v2.0.0b18
Steves Factory Manager vA93
Storage Drawers v1.6.0
Super Massive Tech v0.1.0-alpha-112
Thaumcraft 4 v4.2.3.5
ThaumcraftNEIPlugin v1.7a
Thaumic Energistics v0.8.10.10
Thaumic Exploration v1.1-37
Thaumic Tinkerer v2.5-508
Thermal Dynamics v1.1.0-161
Thermal Expansion v4.0.3B1-218
Thermal Foundation v1.2.0-102
Tinkers Construct v1.8.7-979
Tinkers Mechworks v0.2.14.100
Tinkers Steelworks v1.1.1-17
Tinkers Tooltips v1.2.4
TPPI-Tweaks v1.2.0-123
Translocators v1.1.2.15
Twilight Forest v2.3.7
Waila v1.5.10
Waila Plugins v0.1.2-21
Wawla v1.3.1
Wireless Redstone v1.4.1.9
Witchery v0.24.1
Xaero's Minimap v1.6.1.1
Ztones v2.2.1
Realistic World Gen
RotaryCraft
ChromatiCraft
Hunger Overhaul
Wee! Flowers!
HarvestCraft
Some parts of GrowthCraft
Dynmap
Big Trees

Serverside only:
chunkgen v1.2.3
Morpheus v1.6.10
ServerTools PERMISSION v2.2.1.7
ServerTools TELEPORTATION v2.2.0.13

**Comment by Corosauce** [comment]
Hmmmm interesting thanks for the info, I'll comb over my active client side things in CoroUtil to see what the heavy hitters could be, can't think of anything off the top of my head. 

Regarding TPS for high player counts, I'm not all that sure how well CoroUtil scales with higher player counts, depends on which of my mods you are using too, since CoroUtil on its own isnt all that usefull. Zombie Awareness might cause high cpu usage due to my threaded pathfinder and making the zombies able to track players better.

**Comment by bloxgate** [comment]
The only mod we were using that used CoroUtil was Weather2, I wouldn't
expect that to have major impact server side.

**Comment by Corosauce** [comment]
Good to know, its probably likely that its more weather2 causing FPS issue than CoroUtil, a friend said she couldn't handle weather2 on her older laptop, I suspect it's due to all the calculations run on client side to enhance the visuals of wind like the falling leaves. I've been brainstorming some ideas on ways to improve performance and hope to push some improvements to that in the coming weeks.

In the meantime if you are bored enough and want to try, for server TPS issues, if you have lots of players (like 5-10+), setting both Misc_simBoxRadiusSpawn and Misc_simBoxRadiusCutoff from 1024 to 512 or less might help, makes clouds and storms do less work I think, been a while since I've dived so deep into the code.

For client FPS issues, try either increasing value Thread_Particle_Process_Delay to something huge to basically stop the thread from updating, or to stop client side wind calculations entirely, set Wind_Particle_waterfall Wind_Particle_sand Wind_Particle_leafs Wind_Particle_air all to false. I'm not certain, but I have a theory those features destroy some older computers FPS, I'm going to do some testing in future to see if that theory holds true.
